enum ENVIRONMENT {
  DEV = 'development',
  PROD = 'production',
  TEST = 'test',
}

enum CONFIG {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  API_PREFIX = 'API_PREFIX',
  API_DEFAULT_VERSION = 'API_DEFAULT_VERSION',
  DB_NAME = 'DB_NAME',
  DB_URI = 'DB_URI',
  HASHING_ALGORITHM = 'HASHING_ALGORITHM',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  ACCESS_TOKEN_ALGORITHM = 'ACCESS_TOKEN_ALGORITHM',
  REFRESH_TOKEN_ALGORITHM = 'REFRESH_TOKEN_ALGORITHM',
  ACCESS_TOKEN_EXPIRY = 'ACCESS_TOKEN_EXPIRY',
  REFRESH_TOKEN_EXPIRY = 'REFRESH_TOKEN_EXPIRY',
  JWT_TOKEN_ISSUER = 'JWT_TOKEN_ISSUER',
}

enum SOCIAL_SIGNUP_METHOD {
  GOOGLE = 'google',
  FACEBOOK = 'facebook',
}

enum HASHING_ALGORITHM {
  SHA256 = 'sha256',
  SHA384 = 'sha384',
  SHA512 = 'sha512',
}

enum AUTH_TOKEN_ALGORITHM {
  HS256 = 'HS256',
  HS512 = 'HS512',
  RS256 = 'RS256',
  RS512 = 'RS512',
}

enum SIGNUP_METHOD {
  MANUAL = 'manual',
  GOOGLE = 'google',
  FACEBOOK = 'facebook',
}

enum ROLE {
  ADMIN = 'admin',
  SELLER = 'seller',
  CUSTOMER = 'customer',
}

export {
  ENVIRONMENT,
  CONFIG,
  SOCIAL_SIGNUP_METHOD,
  SIGNUP_METHOD,
  ROLE,
  HASHING_ALGORITHM,
  AUTH_TOKEN_ALGORITHM,
};
